version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_URI
  build:
    commands:
      - docker build -t 2048-game .
      - docker tag 2048-game:latest $ECR_URI:latest
  post_build:
    commands:
      - docker push $ECR_URI:latest
      - printf '[{"name":"2048-game","imageUri":"%s"}]' $ECR_URI:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json